Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

  config.vm.network "public_network", bridge: "br0"

  config.vm.define "Debian"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Debian"
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.hostname = "Debian"

  config.vm.provision "shell", inline: <<-SHELL
  apt install nginx -y #shell script
  #...
SHELL
end
